services:
  movie-streaming:
    build: .
    container_name: movie-streaming
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-5992}
      - APP_URL=${APP_URL:-https://watch.pallabdev.in}
    labels:
      caddy: ${DOMAIN:-watch.pallabdev.in}
      caddy.reverse_proxy: '{{upstreams ${PORT:-5992}}}'
    networks:
      - caddy_net

networks:
  caddy_net:
    name: caddy_net
    external: true
